name: pup-pulse
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch::pytorch=2.0.1
  - pytorch::torchvision=0.15.2
  - pytorch::torchaudio=2.0.2
  - numpy=1.24.3
  - pillow=9.5.0
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - pyyaml=6.0
  - tqdm=4.65.0
  - seaborn=0.12.2
  - pandas=2.0.2
  - pip
  - pip:
    - opencv-python==4.7.1.72

# M1 Mac specific notes:
# - PyTorch with MPS (Metal Performance Shaders) support for GPU acceleration
# - All packages are compatible with Apple Silicon
# - No special compilation flags needed with conda
